version: "3"
services:
  cours-jdbc:
    image: cours-jdbc
    ports:
      - "9191:9191"
    networks:
      - network-cours
    depends_on:
      - mysql

  mysql:
    image: mysql
    networks:
      - network-cours
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=coursdb

networks:
  network-cours:
