version: '3'
services:
  eureka-server:
    image: docker-discovery:0.0.1-SNAPSHOT
    container_name: eurekacontainer
    ports:
      - 8761:8761
    networks:
      - micro-network
    volumes:
      - micro-volume:/chargement
    hostname: eureka
  client:
    image: docker-client-cours-enseignant:0.0.1-SNAPSHOT
    container_name: clientcoursenseignant
    environment:
      - JAVA_OPTS=
        - DEUREKA_SERVER=http:eurekacontainer:8761/eureka
        - Dspring.profiles.active=production
    restart: on-failure
    depends_on:
      - eureka-server
    ports:
      - 9093:9093
    networks:
      - micro-network
    volumes:
      - micro-volume:/chargement
    links:
      - eureka-server
  cours:
    image: docker-cours:0.0.1-SNAPSHOT
    container_name: courscontainer
    environment:
      - JAVA_OPTS=
        - DEUREKA_SERVER=http://eurekacontainer:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - 9090:9090
    networks:
      - micro-network
    volumes:
      - micro-volume:/chargement
    links:
      - eureka-server
  enseignant:
    image: docker-enseignant:0.0.1-SNAPSHOT
    container_name: enseignantcontainer
    environment:
      - JAVA_OPTS=
        - DEUREKA_SERVER=http://eurekacontainer:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - 9091:9091
    networks:
      - micro-network
    volumes:
      - micro-volume:/chargement
    links:
      - eureka-server
  cours-enseignant:
    image: docker-cours-enseignant:0.0.1-SNAPSHOT
    container_name: coursenseignantcontainer
    environment:
      - JAVA_OPTS=
       - DEUREKA_SERVER=http://eurekacontainer:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - 9092:9092
    networks:
      - micro-network
    volumes:
      - micro-volume:/chargement
    links:
      - eureka-server
networks:
  micro-network:
volumes:
  micro-volume:
